[package]
name = "volery"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bincode = "1.3.3"
bon = "3.1.1"
serde = { version = "1.0.215", features = ["derive"] }
smol = "2.0.2"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
